### PR TITLE
Remove some concurrency in mbd_dipole to prevent crash

### PR DESCRIPTION
**Pull request by afonari**
This somehow prevents crash reported in https://github.com/libmbd/libmbd/issues/39.

### CODE REVIEW

**Comment by afonari** [comment]
Now all the fortran tests are passing with ifort and openmp (FFLAGS are coming from the QE make file):
```
FC=ifort FFLAGS="-O2 -assume byterecl -g -traceback -fopenmp -nomodule -fpp" cmake -B build_21_patch && make -C build_21_patch && ctest --test-dir build_21_patch
-- The Fortran compiler identification is Intel 2021.5.0.20211109
-- The C compiler identification is GNU 4.8.5
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /software/lib/Linux-x86_64/ifort_2022.0.2/bin/intel64/ifort - skipped
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Setting version tag to 0.12.5-8-gb203a1a.dirty from Git
-- Setting build type to Debug as none was set
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - not found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - found
-- Found BLAS: /software/lib/Linux-x86_64/ifort_2022.0.2/mkl/lib/intel64/libmkl_intel_lp64.so;/software/lib/Linux-x86_64/ifort_2022.0.2/mkl/lib/intel64/libmkl_intel_thread.so;/software/lib/Linux-x86_64/ifort_2022.0.2/mkl/lib/intel64/libmkl_core.so;/software/lib/Linux-x86_64/ifort_2022.0.2/compiler/lib/intel64/libiomp5.so;-lpthread;-lm;-ldl  
-- Looking for Fortran cheev
-- Looking for Fortran cheev - found
-- Found LAPACK: /software/lib/Linux-x86_64/ifort_2022.0.2/mkl/lib/intel64/libmkl_intel_lp64.so;/software/lib/Linux-x86_64/ifort_2022.0.2/mkl/lib/intel64/libmkl_intel_thread.so;/software/lib/Linux-x86_64/ifort_2022.0.2/mkl/lib/intel64/libmkl_core.so;/software/lib/Linux-x86_64/ifort_2022.0.2/compiler/lib/intel64/libiomp5.so;-lpthread;-lm;-ldl;-lpthread;-lm;-ldl  
-- Configuring done
-- Generating done
-- Build files have been written to: /scr/fonari/libmbd/build_21_patch
make: Entering directory `/scr/fonari/libmbd/build_21_patch'
make[1]: Entering directory `/scr/fonari/libmbd/build_21_patch'
make[2]: Entering directory `/scr/fonari/libmbd/build_21_patch'
Scanning dependencies of target mbd
make[2]: Leaving directory `/scr/fonari/libmbd/build_21_patch'
make[2]: Entering directory `/scr/fonari/libmbd/build_21_patch'
[  3%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_constants.f90.o
[  7%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_defaults.f90.o
[ 11%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_gradients.f90.o
[ 14%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_utils.F90.o
[ 18%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_damping.F90.o
[ 22%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_formulas.f90.o
[ 25%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_lapack.f90.o
[ 29%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_vdw_param.f90.o
[ 33%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_geom.F90.o
[ 37%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_linalg.F90.o
[ 40%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_matrix.F90.o
[ 44%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_dipole.F90.o
[ 48%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_hamiltonian.F90.o
[ 51%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_rpa.F90.o
[ 55%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_scs.f90.o
[ 59%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_methods.F90.o
[ 62%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_ts.F90.o
[ 66%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_version.f90.o
[ 70%] Building Fortran object src/CMakeFiles/mbd.dir/mbd.F90.o
[ 74%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_coulomb.f90.o
[ 77%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_c_api.F90.o
[ 81%] Linking Fortran shared library libmbd.so
make[2]: Leaving directory `/scr/fonari/libmbd/build_21_patch'
[ 81%] Built target mbd
make[2]: Entering directory `/scr/fonari/libmbd/build_21_patch'
Scanning dependencies of target mbd_grad_tests
make[2]: Leaving directory `/scr/fonari/libmbd/build_21_patch'
make[2]: Entering directory `/scr/fonari/libmbd/build_21_patch'
[ 85%] Building Fortran object tests/CMakeFiles/mbd_grad_tests.dir/mbd_grad_test_cases.f90.o
[ 88%] Building Fortran object tests/CMakeFiles/mbd_grad_tests.dir/mbd_grad_tests.F90.o
[ 92%] Linking Fortran executable mbd_grad_tests
make[2]: Leaving directory `/scr/fonari/libmbd/build_21_patch'
[ 92%] Built target mbd_grad_tests
make[2]: Entering directory `/scr/fonari/libmbd/build_21_patch'
Scanning dependencies of target mbd_api_tests
make[2]: Leaving directory `/scr/fonari/libmbd/build_21_patch'
make[2]: Entering directory `/scr/fonari/libmbd/build_21_patch'
[ 96%] Building Fortran object tests/CMakeFiles/mbd_api_tests.dir/mbd_api_tests.F90.o
[100%] Linking Fortran executable mbd_api_tests
make[2]: Leaving directory `/scr/fonari/libmbd/build_21_patch'
[100%] Built target mbd_api_tests
make[1]: Leaving directory `/scr/fonari/libmbd/build_21_patch'
make: Leaving directory `/scr/fonari/libmbd/build_21_patch'
Internal ctest changing into directory: /scr/fonari/libmbd/build_21_patch
Test project /scr/fonari/libmbd/build_21_patch
      Start  1: grad/T_bare_deriv
 1/42 Test  #1: grad/T_bare_deriv .......................   Passed    0.04 sec
      Start  2: grad/T_GG_deriv_expl
 2/42 Test  #2: grad/T_GG_deriv_expl ....................   Passed    0.03 sec
      Start  3: grad/T_GG_deriv_impl
 3/42 Test  #3: grad/T_GG_deriv_impl ....................   Passed    0.03 sec
      Start  4: grad/T_fermi_deriv_impl
 4/42 Test  #4: grad/T_fermi_deriv_impl .................   Passed    0.03 sec
      Start  5: grad/T_erfc_deriv_expl
 5/42 Test  #5: grad/T_erfc_deriv_expl ..................   Passed    0.03 sec
      Start  6: grad/mbd_deriv_expl
 6/42 Test  #6: grad/mbd_deriv_expl .....................   Passed    0.04 sec
      Start  7: grad/mbd_ewald_deriv_expl
 7/42 Test  #7: grad/mbd_ewald_deriv_expl ...............   Passed    0.13 sec
      Start  8: grad/mbd_ewald_deriv_impl_q
 8/42 Test  #8: grad/mbd_ewald_deriv_impl_q .............   Passed    0.08 sec
      Start  9: grad/mbd_ewald_deriv_stress
 9/42 Test  #9: grad/mbd_ewald_deriv_stress .............   Passed    0.19 sec
      Start 10: grad/scs_deriv_expl
10/42 Test #10: grad/scs_deriv_expl .....................   Passed    0.05 sec
      Start 11: grad/scs_ewald_deriv_expl
11/42 Test #11: grad/scs_ewald_deriv_expl ...............   Passed    0.06 sec
      Start 12: grad/scs_ewald_deriv_stress
12/42 Test #12: grad/scs_ewald_deriv_stress .............   Passed    0.07 sec
      Start 13: grad/mbd_deriv_impl_alpha
13/42 Test #13: grad/mbd_deriv_impl_alpha ...............   Passed    0.04 sec
      Start 14: grad/mbd_ewald_deriv_impl_alpha
14/42 Test #14: grad/mbd_ewald_deriv_impl_alpha .........   Passed    0.07 sec
      Start 15: grad/mbd_deriv_impl_omega
15/42 Test #15: grad/mbd_deriv_impl_omega ...............   Passed    0.04 sec
      Start 16: grad/mbd_ewald_deriv_impl_omega
16/42 Test #16: grad/mbd_ewald_deriv_impl_omega .........   Passed    0.08 sec
      Start 17: grad/mbd_deriv_impl_vdw
17/42 Test #17: grad/mbd_deriv_impl_vdw .................   Passed    0.04 sec
      Start 18: grad/mbd_ewald_deriv_impl_vdw
18/42 Test #18: grad/mbd_ewald_deriv_impl_vdw ...........   Passed    0.07 sec
      Start 19: grad/mbd_rsscs_deriv_expl
19/42 Test #19: grad/mbd_rsscs_deriv_expl ...............   Passed    0.06 sec
      Start 20: grad/mbd_rsscs_ewald_deriv_expl
20/42 Test #20: grad/mbd_rsscs_ewald_deriv_expl .........   Passed    1.17 sec
      Start 21: grad/mbd_rsscs_ewald_deriv_stress
21/42 Test #21: grad/mbd_rsscs_ewald_deriv_stress .......   Passed    1.85 sec
      Start 22: grad/mbd_rsscs_deriv_impl_alpha
22/42 Test #22: grad/mbd_rsscs_deriv_impl_alpha .........   Passed    0.05 sec
      Start 23: grad/mbd_rsscs_deriv_impl_C6
23/42 Test #23: grad/mbd_rsscs_deriv_impl_C6 ............   Passed    0.04 sec
      Start 24: grad/mbd_rsscs_deriv_impl_vdw
24/42 Test #24: grad/mbd_rsscs_deriv_impl_vdw ...........   Passed    0.07 sec
      Start 25: grad/mbd_rsscs_ewald_deriv_impl_alpha
25/42 Test #25: grad/mbd_rsscs_ewald_deriv_impl_alpha ...   Passed    0.41 sec
      Start 26: grad/mbd_rsscs_ewald_deriv_impl_C6
26/42 Test #26: grad/mbd_rsscs_ewald_deriv_impl_C6 ......   Passed    0.42 sec
      Start 27: grad/mbd_rsscs_ewald_deriv_impl_vdw
27/42 Test #27: grad/mbd_rsscs_ewald_deriv_impl_vdw .....   Passed    0.44 sec
      Start 28: grad/ts_deriv_expl
28/42 Test #28: grad/ts_deriv_expl ......................   Passed    0.02 sec
      Start 29: grad/ts_ewald_deriv_expl
29/42 Test #29: grad/ts_ewald_deriv_expl ................   Passed    0.07 sec
      Start 30: grad/ts_ewald_deriv_stress
30/42 Test #30: grad/ts_ewald_deriv_stress ..............   Passed    0.07 sec
      Start 31: grad/ts_deriv_impl_alpha
31/42 Test #31: grad/ts_deriv_impl_alpha ................   Passed    0.02 sec
      Start 32: grad/ts_deriv_impl_C6
32/42 Test #32: grad/ts_deriv_impl_C6 ...................   Passed    0.02 sec
      Start 33: grad/ts_deriv_impl_vdw
33/42 Test #33: grad/ts_deriv_impl_vdw ..................   Passed    0.03 sec
      Start 34: grad/ts_ewald_deriv_impl_alpha
34/42 Test #34: grad/ts_ewald_deriv_impl_alpha ..........   Passed    0.06 sec
      Start 35: grad/ts_ewald_deriv_impl_C6
35/42 Test #35: grad/ts_ewald_deriv_impl_C6 .............   Passed    0.05 sec
      Start 36: grad/ts_ewald_deriv_impl_vdw
36/42 Test #36: grad/ts_ewald_deriv_impl_vdw ............   Passed    0.06 sec
      Start 37: api/exception
37/42 Test #37: api/exception ...........................   Passed    0.02 sec
      Start 38: api/energy
38/42 Test #38: api/energy ..............................   Passed    0.04 sec
      Start 39: api/gradients
39/42 Test #39: api/gradients ...........................   Passed    0.04 sec
      Start 40: api/energy_from_ratios
40/42 Test #40: api/energy_from_ratios ..................   Passed    0.04 sec
      Start 41: api/hirshfeld_gradients
41/42 Test #41: api/hirshfeld_gradients .................   Passed    0.04 sec
      Start 42: api/ts_gradients
42/42 Test #42: api/ts_gradients ........................   Passed    0.02 sec

100% tests passed, 0 tests failed out of 42

Total Test time (real) =   6.26 sec
```

**Comment by jhrmnn** [comment]
Thanks for the effort, but I'm reluctant to include constructs just to avoid compiler bugs, unless there is a very good reason for it. Has this been fixed in recent Ifort versions?

**Comment by afonari** [comment]
> Has this been fixed in recent Ifort versions?

`2021.5.0.20211109` is the latest version, see https://www.intel.com/content/www/us/en/developer/articles/release-notes/oneapi-fortran-compiler-release-notes.html

**Comment by jhrmnn** [comment]
Ok, I've pushed some changes.
- I've renamed the macro def to something semantically more generic.
- I removed the auto determination of the macro—I don't want to deal with these kind of tricky issues in the code. If the compiler is buggy, the user needs to supply the macro manually.
- I refactored the patch so that there are only line additions, no line changes, in the `src` files. This will make it easier to revert the patch once the Intel compiler is fixed. Please, refactor the test file accordingly, then I'll merge.

**Comment by afonari** [comment]
Thanks, will update tests. Maybe a name constant that has ifort in it would be more helpful for the users, like: `WITHOUT_IFORT_DO_CONCURRENT`?

**Comment by afonari** [comment]
Updated tests, all tests pass, ran with (note `-DWITHOUT_DO_CONCURRENT=1`):
```
FC=ifort FFLAGS="-O2 -assume byterecl -g -traceback -qopenmp -nomodule -fpp -DWITHOUT_DO_CONCURRENT=1" cmake -B build_21_patch && make -C build_21_patch && ctest --test-dir build_21_patch
-- The Fortran compiler identification is Intel 2021.5.0.20211109
-- The C compiler identification is GNU 4.8.5
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /software/lib/Linux-x86_64/ifort_2022.0.2/bin/intel64/ifort - skipped
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Setting version tag to 0.12.5-11-g63b7fba from Git
-- Setting build type to Debug as none was set
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - not found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - found
-- Found BLAS: /software/lib/Linux-x86_64/ifort_2022.0.2/mkl/lib/intel64/libmkl_intel_lp64.so;/software/lib/Linux-x86_64/ifort_2022.0.2/mkl/lib/intel64/libmkl_intel_thread.so;/software/lib/Linux-x86_64/ifort_2022.0.2/mkl/lib/intel64/libmkl_core.so;/software/lib/Linux-x86_64/ifort_2022.0.2/compiler/lib/intel64/libiomp5.so;-lpthread;-lm;-ldl  
-- Looking for Fortran cheev
-- Looking for Fortran cheev - found
-- Found LAPACK: /software/lib/Linux-x86_64/ifort_2022.0.2/mkl/lib/intel64/libmkl_intel_lp64.so;/software/lib/Linux-x86_64/ifort_2022.0.2/mkl/lib/intel64/libmkl_intel_thread.so;/software/lib/Linux-x86_64/ifort_2022.0.2/mkl/lib/intel64/libmkl_core.so;/software/lib/Linux-x86_64/ifort_2022.0.2/compiler/lib/intel64/libiomp5.so;-lpthread;-lm;-ldl;-lpthread;-lm;-ldl  
-- Configuring done
-- Generating done
-- Build files have been written to: /scr/fonari/libmbd/build_21_patch
make: Entering directory `/scr/fonari/libmbd/build_21_patch'
make[1]: Entering directory `/scr/fonari/libmbd/build_21_patch'
make[2]: Entering directory `/scr/fonari/libmbd/build_21_patch'
Scanning dependencies of target mbd
make[2]: Leaving directory `/scr/fonari/libmbd/build_21_patch'
make[2]: Entering directory `/scr/fonari/libmbd/build_21_patch'
[  3%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_constants.f90.o
[  7%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_defaults.f90.o
[ 11%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_gradients.f90.o
[ 14%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_utils.F90.o
[ 18%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_damping.F90.o
[ 22%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_formulas.f90.o
[ 25%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_lapack.f90.o
[ 29%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_vdw_param.f90.o
[ 33%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_geom.F90.o
[ 37%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_linalg.F90.o
[ 40%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_matrix.F90.o
[ 44%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_dipole.F90.o
[ 48%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_hamiltonian.F90.o
[ 51%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_rpa.F90.o
[ 55%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_scs.f90.o
[ 59%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_methods.F90.o
[ 62%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_ts.F90.o
[ 66%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_version.f90.o
[ 70%] Building Fortran object src/CMakeFiles/mbd.dir/mbd.F90.o
[ 74%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_coulomb.f90.o
[ 77%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_c_api.F90.o
[ 81%] Linking Fortran shared library libmbd.so
make[2]: Leaving directory `/scr/fonari/libmbd/build_21_patch'
[ 81%] Built target mbd
make[2]: Entering directory `/scr/fonari/libmbd/build_21_patch'
Scanning dependencies of target mbd_grad_tests
make[2]: Leaving directory `/scr/fonari/libmbd/build_21_patch'
make[2]: Entering directory `/scr/fonari/libmbd/build_21_patch'
[ 85%] Building Fortran object tests/CMakeFiles/mbd_grad_tests.dir/mbd_grad_test_cases.f90.o
[ 88%] Building Fortran object tests/CMakeFiles/mbd_grad_tests.dir/mbd_grad_tests.F90.o
[ 92%] Linking Fortran executable mbd_grad_tests
make[2]: Leaving directory `/scr/fonari/libmbd/build_21_patch'
[ 92%] Built target mbd_grad_tests
make[2]: Entering directory `/scr/fonari/libmbd/build_21_patch'
Scanning dependencies of target mbd_api_tests
make[2]: Leaving directory `/scr/fonari/libmbd/build_21_patch'
make[2]: Entering directory `/scr/fonari/libmbd/build_21_patch'
[ 96%] Building Fortran object tests/CMakeFiles/mbd_api_tests.dir/mbd_api_tests.F90.o
[100%] Linking Fortran executable mbd_api_tests
make[2]: Leaving directory `/scr/fonari/libmbd/build_21_patch'
[100%] Built target mbd_api_tests
make[1]: Leaving directory `/scr/fonari/libmbd/build_21_patch'
make: Leaving directory `/scr/fonari/libmbd/build_21_patch'
Internal ctest changing into directory: /scr/fonari/libmbd/build_21_patch
Test project /scr/fonari/libmbd/build_21_patch
      Start  1: grad/T_bare_deriv
 1/42 Test  #1: grad/T_bare_deriv .......................   Passed    0.49 sec
      Start  2: grad/T_GG_deriv_expl
 2/42 Test  #2: grad/T_GG_deriv_expl ....................   Passed    0.05 sec
      Start  3: grad/T_GG_deriv_impl
 3/42 Test  #3: grad/T_GG_deriv_impl ....................   Passed    0.03 sec
      Start  4: grad/T_fermi_deriv_impl
 4/42 Test  #4: grad/T_fermi_deriv_impl .................   Passed    0.03 sec
      Start  5: grad/T_erfc_deriv_expl
 5/42 Test  #5: grad/T_erfc_deriv_expl ..................   Passed    0.03 sec
      Start  6: grad/mbd_deriv_expl
 6/42 Test  #6: grad/mbd_deriv_expl .....................   Passed    0.60 sec
      Start  7: grad/mbd_ewald_deriv_expl
 7/42 Test  #7: grad/mbd_ewald_deriv_expl ...............   Passed    1.07 sec
      Start  8: grad/mbd_ewald_deriv_impl_q
 8/42 Test  #8: grad/mbd_ewald_deriv_impl_q .............   Passed    0.77 sec
      Start  9: grad/mbd_ewald_deriv_stress
 9/42 Test  #9: grad/mbd_ewald_deriv_stress .............   Passed    0.70 sec
      Start 10: grad/scs_deriv_expl
10/42 Test #10: grad/scs_deriv_expl .....................   Passed    0.06 sec
      Start 11: grad/scs_ewald_deriv_expl
11/42 Test #11: grad/scs_ewald_deriv_expl ...............   Passed    0.34 sec
      Start 12: grad/scs_ewald_deriv_stress
12/42 Test #12: grad/scs_ewald_deriv_stress .............   Passed    0.57 sec
      Start 13: grad/mbd_deriv_impl_alpha
13/42 Test #13: grad/mbd_deriv_impl_alpha ...............   Passed    0.05 sec
      Start 14: grad/mbd_ewald_deriv_impl_alpha
14/42 Test #14: grad/mbd_ewald_deriv_impl_alpha .........   Passed    0.16 sec
      Start 15: grad/mbd_deriv_impl_omega
15/42 Test #15: grad/mbd_deriv_impl_omega ...............   Passed    0.04 sec
      Start 16: grad/mbd_ewald_deriv_impl_omega
16/42 Test #16: grad/mbd_ewald_deriv_impl_omega .........   Passed    0.43 sec
      Start 17: grad/mbd_deriv_impl_vdw
17/42 Test #17: grad/mbd_deriv_impl_vdw .................   Passed    0.06 sec
      Start 18: grad/mbd_ewald_deriv_impl_vdw
18/42 Test #18: grad/mbd_ewald_deriv_impl_vdw ...........   Passed    0.46 sec
      Start 19: grad/mbd_rsscs_deriv_expl
19/42 Test #19: grad/mbd_rsscs_deriv_expl ...............   Passed    0.19 sec
      Start 20: grad/mbd_rsscs_ewald_deriv_expl
20/42 Test #20: grad/mbd_rsscs_ewald_deriv_expl .........   Passed   12.53 sec
      Start 21: grad/mbd_rsscs_ewald_deriv_stress
21/42 Test #21: grad/mbd_rsscs_ewald_deriv_stress .......   Passed   21.54 sec
      Start 22: grad/mbd_rsscs_deriv_impl_alpha
22/42 Test #22: grad/mbd_rsscs_deriv_impl_alpha .........   Passed    0.12 sec
      Start 23: grad/mbd_rsscs_deriv_impl_C6
23/42 Test #23: grad/mbd_rsscs_deriv_impl_C6 ............   Passed    0.10 sec
      Start 24: grad/mbd_rsscs_deriv_impl_vdw
24/42 Test #24: grad/mbd_rsscs_deriv_impl_vdw ...........   Passed    0.11 sec
      Start 25: grad/mbd_rsscs_ewald_deriv_impl_alpha
25/42 Test #25: grad/mbd_rsscs_ewald_deriv_impl_alpha ...   Passed    6.22 sec
      Start 26: grad/mbd_rsscs_ewald_deriv_impl_C6
26/42 Test #26: grad/mbd_rsscs_ewald_deriv_impl_C6 ......   Passed    4.18 sec
      Start 27: grad/mbd_rsscs_ewald_deriv_impl_vdw
27/42 Test #27: grad/mbd_rsscs_ewald_deriv_impl_vdw .....   Passed    4.73 sec
      Start 28: grad/ts_deriv_expl
28/42 Test #28: grad/ts_deriv_expl ......................   Passed    0.02 sec
      Start 29: grad/ts_ewald_deriv_expl
29/42 Test #29: grad/ts_ewald_deriv_expl ................   Passed    0.07 sec
      Start 30: grad/ts_ewald_deriv_stress
30/42 Test #30: grad/ts_ewald_deriv_stress ..............   Passed    0.12 sec
      Start 31: grad/ts_deriv_impl_alpha
31/42 Test #31: grad/ts_deriv_impl_alpha ................   Passed    0.02 sec
      Start 32: grad/ts_deriv_impl_C6
32/42 Test #32: grad/ts_deriv_impl_C6 ...................   Passed    0.02 sec
      Start 33: grad/ts_deriv_impl_vdw
33/42 Test #33: grad/ts_deriv_impl_vdw ..................   Passed    0.02 sec
      Start 34: grad/ts_ewald_deriv_impl_alpha
34/42 Test #34: grad/ts_ewald_deriv_impl_alpha ..........   Passed    0.05 sec
      Start 35: grad/ts_ewald_deriv_impl_C6
35/42 Test #35: grad/ts_ewald_deriv_impl_C6 .............   Passed    0.05 sec
      Start 36: grad/ts_ewald_deriv_impl_vdw
36/42 Test #36: grad/ts_ewald_deriv_impl_vdw ............   Passed    0.05 sec
      Start 37: api/exception
37/42 Test #37: api/exception ...........................   Passed    0.02 sec
      Start 38: api/energy
38/42 Test #38: api/energy ..............................   Passed    0.06 sec
      Start 39: api/gradients
39/42 Test #39: api/gradients ...........................   Passed    0.04 sec
      Start 40: api/energy_from_ratios
40/42 Test #40: api/energy_from_ratios ..................   Passed    0.05 sec
      Start 41: api/hirshfeld_gradients
41/42 Test #41: api/hirshfeld_gradients .................   Passed    0.05 sec
      Start 42: api/ts_gradients
42/42 Test #42: api/ts_gradients ........................   Passed    0.02 sec

100% tests passed, 0 tests failed out of 42

Total Test time (real) =  56.38 sec```

**Comment by jhrmnn** [comment]
Ok, looks good now! Thanks for reporting and coming up with the PR.

> Thanks, will update tests. Maybe a name constant that has ifort in it would be more helpful for the users, like: `WITHOUT_IFORT_DO_CONCURRENT`?

Actually, my goal is exactly the opposite, to make no reference to a particular compiler. As it stands, the macro name is meaningful even without knowing about this particular issue. One could even use for other purposes, perhaps to support an old Gfortran that lacked support for `do concurrent`.

**Comment by afonari** [comment]
Thanks for merging. Apparently it should be possible to run github workflows with ifort:
https://github.com/oneapi-src/oneapi-ci/blob/master/.github/workflows/build_all.yml
https://github.com/dftbplus/dftbplus/blob/main/.github/workflows/build.yml

This would catch this bug (I think). Would you be open to add ifort to CI?

**Comment by ye-luo** [comment]
It seem lacking a CMake option to toggle on/off "do concurrent". Need it for integrating to other CMake projects.
```
if(QE_ENABLE_OPENMP)
  set(MDB_USE_DO_CONCURRENT OFF)
endif()
add_subdirectory(mbd)
```

**Comment by ye-luo** [comment]
I meant the `WITHOUT_DO_CONCURRENT` added in this PR doesn't have a corresponding option accessible in CMake. Building MBD as a standalone library, the macro can be injected in `CMAKE_Fortran_FLAGS`. However, when mbd is incorporated in another CMake project, user setting the macro to the global `CMAKE_Fortran_FLAGS` is cumbersome. Here I'm requesting a CMake option which handles the macro internally in the CMake of the MBD library.

**Comment by jhrmnn** [comment]
Ah. Got it. Yeah, that can be done. Please either make an issue or a PR so I don't lose track of it.

**Comment by jhrmnn** [comment]
I looked into a bit. Can't you just use [`add_compile_definitions`](https://cmake.org/cmake/help/latest/command/add_compile_definitions.html) or [`target_compile_definitions`](https://cmake.org/cmake/help/latest/command/target_compile_definitions.html) in the superproject?

**Comment by ye-luo** [comment]
Technically `target_compile_definitions` likely works. However, I don't think this is a good software practice.

**Comment by jhrmnn** [comment]
If the macro definition was related to optional functionality, I'd agree that it should have an explicit user option. But since this is just handling outdated compilers that don't understand modern Fortran, I'm fine with having this only accessible through a bit of a hack. Hopefully the hack can be removed once the support for the outdated compilers is dropped.

**Comment by ye-luo** [comment]
I won't consider Intel `2021.5.0.20211109` that old (within 2 years). I have not tested the latest ifx compiler from Intel. Can revisit once we have more data points.

**Pull request merged**
